version: "3.9"

services:

  db-postgres:
    image: postgres:13
    container_name: uptc-register-postgres
    environment:
      POSTGRES_PASSWORD: "secret"
      POSTGRES_USER: "homestead"
      POSTGRES_DB: "uptc_register"
    volumes: 
      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - uptc-register
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U homestead"]
      interval: 5s
      timeout: 5s
      retries: 3
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: uptc-register-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@example.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db-postgres
    networks:
      - uptc-register

  registro-uptc:
    build:
      context: ../../../Backend
      dockerfile: ../.devops/docker/develop/Dockerfile
    volumes:
      - ./data:/registro/data
    networks:
      - uptc-register
    depends_on:
      db-postgres:
        condition: service_healthy    

networks:
  uptc-register:
    driver: bridge
